apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yiftx74vv-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:2a61b043c37360515d32389ac3371a5e4397b84e@sha256:2997d183a2864e0e19f9741be3b288e1be598dc39ce19ba04d9da7d9ff09f05e
          name: container-image
