apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yiftx74vv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yiftx74vv-python 
  name: yiftx74vv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yiftx74vv-python 
